version: '3.4'
services:
  obol.avado.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: v0.19.2
        NIMBUS_VERSION: v24.2.2
        TEKU_VERSION: 24.2.0
    image: 'obol.avado.dappnode.eth:0.0.12'
    restart: always
    volumes:
      - 'data:/data'
    environment:
      - NETWORK=mainnet
    ports:
      - '3610:3610'
      - '3620:3620'
      - '9999:9999'
      - '80:80'
      - '5052:5052'
volumes:
  data: {}
